### ISSUE TITLE
double query ke mysql

### ISSUE THREAD

**Issue by madededy** [kiddyatreides/fastify-todo-with-auth#1]
bang, terima kasih ya buat tutorialnya. 
tapi pas dicoba setiap kali running ternyata dia ngejalanin 2 kali query ke mysql. 
jadi pas POST malah muncul 2 baris di databasenya, setelah coba ku di comment file routes.js line 18 - 21, akhirnya mau normal.

```
//   fastify.addHook('preHandler', async (request, reply, next) => {
//        await middleware.check(request, reply);
//       next();
//    });
```

**Comment by kiddyxyz** [comment]
Wah oke issue ini segera saya benerin ya.

**Comment by perogeremmer** [comment]
Terimakasih telah mengingatkan, solved ya.
